version: '3.8'
services:
  backend:
    image: node:18
    container_name: respaldos_backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: respaldos_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cre61650_agenda
      MYSQL_USER: cre61650_respaldos21
      MYSQL_PASSWORD: respaldos21/
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: respaldos_app
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    ports:
      - "80:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: respaldos_pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8082:80"
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    depends_on:
      - db

volumes:
  dbdata:
